export const Questions = [
    "What's the weather?",
    "Tell me a joke",
    "Play relaxing music",
    "What's the time?",
    "How's traffic today?",
    "What’s the latest news?",
    "Set a reminder",
    "Translate this text",
    "Open calculator",
    "Show me a recipe",
    "Play a podcast",
    "Turn on the lights",
    "What's my schedule?",
    "Find nearby restaurants",
    "Check my emails",
    "Start a timer",
    "What's my location?",
    "Tell me a fun fact",
    "Recommend a movie",
    "Open YouTube"
];
