export const Questions = [
    "What is AI?",
    "Tell me a fun fact about space.",
    "Explain the concept of machine learning.",
    "What is the capital of France?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What is 12 multiplied by 15?",
    "How do planes fly?",
    "What’s the speed of light?",
    "Tell me a riddle.",
    "Explain photosynthesis.",
    "What is the tallest mountain on Earth?",
    "How does the internet work?",
    "Why is the sky blue?",
    "Tell me a historical fact.",
    "What are Newton's laws of motion?",
    "How do you say 'hello' in French?",
    "What’s the value of pi?",
    "Explain blockchain technology.",
    "What’s the origin of Halloween?",
    "Describe the life cycle of a butterfly.",
    "What are the three states of matter?",
    "Who was Albert Einstein?",
    "What is the Pythagorean theorem?",
    "How does a car engine work?",
    "What is the function of the human heart?",
    "How do magnets work?",
    "What is the largest ocean on Earth?",
    "Explain the greenhouse effect.",
    "What are the planets in our solar system?",
    "Who painted the Mona Lisa?",
    "What is the boiling point of water?",
    "What is the difference between an asteroid and a comet?",
    "What is the function of DNA?",
    "Explain the water cycle.",
    "Who was the first person to walk on the moon?",
    "What are prime numbers?",
    "What are the seven continents?",
    "What is the Great Wall of China?",
    "What is renewable energy?",
    "What is the formula for calculating the area of a circle?",
    "What is gravity?",
    "What causes a rainbow?",
    "What is the largest animal on Earth?",
    "What is the function of photosynthesis?",
    "Explain the difference between a star and a planet.",
    "What is the main ingredient in bread?",
    "What are the primary colors?",
    "What is a black hole?",
    "Who is the author of 'Harry Potter'?",
    "What is the function of a seed in a plant?"
];
